name: wasm

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: qmaru/wasm-pack-action@v0.5.0
        with:
          version: "latest"

      - run: cargo test
      # - run: wasm-pack build -t bundler --release --scope ${{github.repository_owner}}
      - run: wasm-pack build -t web --release --scope ${{github.repository_owner}}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
      - run: |
          cd pkg
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
