name: wasm

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  wasm-build-publish:
    name: Build & Publish WASM (${{ matrix.target }})
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        target: [bundler, web]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup wasm-pack
        uses: qmaru/wasm-pack-action@v0.5.0
        with:
          version: latest

      - name: Run Tests
        run: cargo test

      - name: Rename package for web (only for web target)
        if: matrix.target == 'web'
        run: sed -i 's#name = "rtools"#name = "rtools-web"#g' Cargo.toml

      - name: Build WASM (${{ matrix.target }} target)
        run: wasm-pack build -t ${{ matrix.target }} --release --scope ${{ github.repository_owner }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"

      - name: Publish npm package
        run: |
          cd pkg
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
